package:
  name: tox
  version: 2.1.1

source:
  fn: tox-2.1.1.tar.gz
  url: https://pypi.python.org/packages/source/t/tox/tox-2.1.1.tar.gz
  md5: fc5b38cce701ced90a89b9da24af1769
#  patches:
   # List any patch files here
   # - fix.patch

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tox = tox:main
    #
    # Would create an entry point called tox that calls tox.main()
    - tox = tox:cmdline
    - tox-quickstart = tox._quickstart:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - argparse [py26]
    - setuptools
    - py
    - virtualenv
    - pluggy

  run:
    - python
    - argparse [py26]
    - py
    - virtualenv
    - pluggy

test:
  # Python imports
  imports:
    - tox


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://tox.testrun.org/
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
