package:
  name: flanker
  version: !!str 0.4.27

source:
  fn: flanker-0.4.27.tar.gz
  url: https://pypi.python.org/packages/source/f/flanker/flanker-0.4.27.tar.gz
  md5: 51ac7ba1fb2e306a85502d0e1932c315
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flanker = flanker:main
    #
    # Would create an entry point called flanker that calls flanker.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - chardet >=1.0.1
    - cchardet >=0.3.5
    - cython >=0.21.1
    - dnsq >=1.1.3
    - expiringdict >=1.1.2
    - webob >=0.9.8
    - redis-py >=2.7.1
    - regex >=0.1.20110315

  run:
    - python
    - chardet >=1.0.1
    - cchardet >=0.3.5
    - cython >=0.21.1
    - dnsq >=1.1.3
    - expiringdict >=1.1.2
    - webob >=0.9.8
    - redis-py >=2.7.1
    - regex >=0.1.20110315

test:
  # Python imports
  imports:
    - flanker
    - flanker.addresslib
    - flanker.addresslib.drivers
    - flanker.addresslib.plugins
    - flanker.mime
    - flanker.mime.message
    - flanker.mime.message.fallback
    - flanker.mime.message.headers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mailgun.net
  license: Apache 2
  summary: 'Mailgun Parsing Tools'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
