package:
  name: unixodbc
  version: 2.3.4

source:
  fn: unixODBC-2.3.4.tar.gz
  md5: bd25d261ca1808c947cb687e2034be81
  url: ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.4.tar.gz


about:
  home: http://www.unixodbc.org/