package:
  name: sseclient
  version: "0.0.8"

source:
  fn: sseclient-0.0.8.tar.gz
  url: https://pypi.python.org/packages/source/s/sseclient/sseclient-0.0.8.tar.gz
  md5: fee976a25b081b6c5e7bb25cdab6098c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sseclient = sseclient:main
    #
    # Would create an entry point called sseclient that calls sseclient.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.0.0
    - six

  run:
    - python
    - requests >=2.0.0
    - six

test:
  # Python imports
  imports:
    - sseclient

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bits.btubbs.com/sseclient
  license: UNKNOWN
  summary: 'Python client library for reading Server Sent Event streams.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
