package:
  name: pyldavis
  version: "1.3.0"

source:
  fn: pyLDAvis-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pyLDAvis/pyLDAvis-1.3.0.tar.gz
  md5: cb64320375e095ea32c94a187e89883b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyldavis = pyldavis:main
    #
    # Would create an entry point called pyldavis that calls pyldavis.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pandas >=0.16
    - numexpr
    - future
    - numpy
    - funcy
    - jinja2 >=2.7.2
    - scikit-bio >=0.2.3
    - joblib >=0.8.4
    - mock

  run:
    - python
    - pandas >=0.16
    - numexpr
    - future
    - numpy
    - funcy
    - jinja2 >=2.7.2
    - scikit-bio >=0.2.3
    - joblib >=0.8.4

test:
  # Python imports
  imports:
    - pyLDAvis

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - funcy
    - pytest
    - mock
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bmabey/pyLDAvis
  license: MIT License
  summary: 'Interactive topic model visualization. Port of the R package.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
