package:
  name: yasm
  version: 1.3.0

requirements:
  build:
    - python

source:
  fn: yasm-1.3.0.tar.gz
  url: http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
  sha256 : 3dce6601b495f5b3d45b59f7d2492a340ee7e84b5beca17e48f862502bd5603f

about:
  home: http://www.tortall.net/projects/yasm/
  license: BSD
  summary: 'Yasm is a complete rewrite of the NASM assembler under the "new" BSD License'
