
package:
    name: pytools
    version: 2014.3.5

source:
    fn: pytools-2014.3.5.tar.gz
    url: https://pypi.python.org/packages/source/p/pytools/pytools-2014.3.5.tar.gz
    md5: 7f8e9d6a88090a601e96a9ee095d3512

build:
    number: 0

requirements:
    build:
        - python
        - distribute
        - decorator
        - six
        - appdirs

    run:
        - python
        - decorator
        - six
        - appdirs

test:
    imports:
        - pytools

about:
    home: https://pypi.python.org/pypi/pytools
    license: MIT

