
package:
    name: spacy
    version: 0.93

source:
    fn: spacy-0.93.tar.gz
    url: https://pypi.python.org/packages/source/s/spacy/spacy-0.93.tar.gz
    md5: 261ffeb5e95c3f9398ed9a8aae066ec4

build:
    number: 1

requirements:
    build:
        - python
        - headers_workaround
        - cython
        - cymem >=1.11
        - preshed
        - thinc
        - murmurhash
        - unidecode
        - numpy
        - pywget
        - plac
        - six
        - ujson

    run:
        - python
        - cython
        - cymem >=1.11
        - preshed
        - thinc
        - murmurhash
        - unidecode
        - numpy
        - pywget
        - plac
        - six
        - ujson

test:
    imports:
        - spacy

about:
    home: http://honnibal.github.io/spaCy/
    license: Commercial or Trial or AGPLv3

