package:
  name: r # [win]
  name: r-base # [not win]
  version: 3.1.2

source:
  fn: R-3.1.2.tar.gz
  url: http://cran.cnr.berkeley.edu/src/base/R-3/R-3.1.2.tar.gz
  sha1: 93809368e5735a630611633ac1fa99010020c5d6
  patches: # [not win]
    - share-make-vars.mk.patch # [not win]
    - mac-unicode.patch # [osx]

build:
  rpaths:
    - lib/R/lib/
    - lib/
  number: 2 # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - readline  # [not win]
    - ncurses   # [not win]
    - tk        # [not win]
    - zlib      # [not win]
    - gsl       # [not win]
    - cairo     # [linux]
    - pango     # [linux]
    - jpeg      # [not win]
    - libpng    # [not win]
    - libtiff   # [not win]
    - libxml2 # Not really sure if libxml2 is needed [not win]
    - gcc       # [not win]
    - pcre      # [not win]

  run:
    - readline  # [not win]
    - ncurses   # [not win]
    - tk        # [not win]
    - zlib      # [not win]
    - cairo     # [linux]
    - pango     # [linux]
    - jpeg      # [not win]
    - libpng    # [not win]
    - libtiff   # [not win]
    - libxml2   # [not win]
    - gcc       # [not win]
    - pcre      # [not win]

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  "cat('ok\n')"
    - open # [win]
    # There doesn't seem to be a way to test this one
    # - RSetReg # [win]
    - Rfe --help # [win]
    - Rterm --help # [win]
    - Rterm --version # [win]
    - exit 1 # [osx]

about:
  home: http://www.r-project.org/
  license: GPL
