package:
  name: erlang
  version: R15B03.1

source:
  fn: otp_src_R15B03-1.tar.gz
  md5: eccd1e6dda6132993555e088005019f2
  url: http://www.erlang.org/download/otp_src_R15B03-1.tar.gz

build:
  number: 0
    
requirements:
  build:
    - readline
    - openssl
    - unixodbc
  run:
    - readline
    - openssl
    - unixodbc

about:
  home: http://www.erlang.org/
  license: Erlang Public License 1.1 (http://www.erlang.org/EPLICENSE)
