package:
  name: tinycss
  version: !!str 0.3

source:
  fn: tinycss-0.3.tar.gz
  url: https://pypi.python.org/packages/source/t/tinycss/tinycss-0.3.tar.gz
  md5: 13999e54453d4fbc9d1539f4b95d235e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tinycss = tinycss:main
    #
    # Would create an entry point called tinycss that calls tinycss.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - tinycss
    - tinycss.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://packages.python.org/tinycss/
  license: BSD License
  summary: 'tinycss is a complete yet simple CSS parser for Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
