package:
  name: futures
  version: 2.2.0

source:
  fn: futures-2.2.0.tar.gz
  url: https://pypi.python.org/packages/source/f/futures/futures-2.2.0.tar.gz
  md5: 310e446de8609ddb59d0886e35edb534
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - futures = futures:main
    #
    # Would create an entry point called futures that calls futures.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - futures

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/pythonfutures
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
