package:
  name: streamparse
  version: "1.1.0"

source:
  fn: streamparse-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/s/streamparse/streamparse-1.1.0.tar.gz
  md5: 31d425d265e0278f7931a0bb6d4b59c4
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - streamparse = streamparse:main
    #
    # Would create an entry point called streamparse that calls streamparse.main()

    - sparse = streamparse.cmdln:main
    - streamparse = streamparse.cmdln:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - invoke
    - fabric
    - docopt
    - jinja2
    - six
    - contextlib2
    - leiningen
    

  run:
    - python
    - invoke
    - fabric
    - docopt
    - jinja2
    - six
    - contextlib2
    - leiningen
    

test:
  # Python imports
  imports:
    - streamparse
    - streamparse.bootstrap
    - streamparse.ext

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - sparse --help
    - streamparse --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Parsely/streamparse
  license: Apache License 2.0
  summary: 'streamparse lets you run Python code against real-time streams of data. Integrates with Apache Storm.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
