package:
  name: monthdelta
  version: !!str 1.0b

source:
  fn: MonthDelta-1.0b.tar.gz
  url: https://pypi.python.org/packages/source/M/MonthDelta/MonthDelta-1.0b.tar.gz
  md5: 0030e741699a1b4d03176e0d13f12864
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - monthdelta = monthdelta:main
    #
    # Would create an entry point called monthdelta that calls monthdelta.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - monthdelta

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/MonthDelta
  license: MIT License
  summary: 'date computations with months'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
