package:
  name: pyqt
  version: "4.11.2"

source: # [unix]
  fn: PyQt-mac-gpl-4.11.2.tar.gz # [osx]
  url: http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.2/PyQt-mac-gpl-4.11.2.tar.gz # [osx]
  sha1: c8534aa008b311ec370fc87a0748b510d6436e60 # [osx]
  fn: PyQt-x11-gpl-4.11.2.tar.gz # [linux]
  url: http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.2/PyQt-x11-gpl-4.11.2.tar.gz # [linux]
  sha1: bf96f7ba29fff4b33205cb2d2d033841494d187e # [linux]
  patches: # [unix]
    - configure.patch # [unix]

requirements:
  build: # [unix]
    - python # [unix]
    - qt # [unix]
    - sip >=4.16.2 # [unix]

  run:
    - python
    - qt # [unix]
    - sip >=4.16.2

test:
  imports:
    - PyQt4

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL
