
package:
    name: scrapy
    version: !!str 0.24.6

source:
    fn: scrapy-0.24.6.tar.gz
    url: https://github.com/scrapy/scrapy/archive/0.24.6.tar.gz
    md5: c4fc7af73e3cafc8000c2a02c5925fb0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - twisted >=10.0.0
        - lxml
        - pyopenssl
        - cssselect >=0.9
        - w3lib >=1.8.0
        - queuelib
        - six >=1.5.2

    run:
        - python
        - setuptools
        - twisted >=10.0.0
        - lxml
        - pyopenssl
        - cssselect >=0.9
        - w3lib >=1.8.0
        - queuelib
        - six >=1.5.2

test:
    imports:
        - scrapy

    commands:
        #- nosetests -w tests/

about:
    home: https://github.com/louist87/Scrappy
    license: GPL v3

