
package:
    name: scrapy
    version: !!str 0.2.44

source:
    fn: scrapy-0.2.44.tar.gz
    url: https://github.com/scrapy/scrapy/archive/0.24.4.tar.gz
    md5: e15f4ca2c6d13467225b20699338ccab

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - twisted >=10.0.0
        - lxml
        - pyopenssl
        - cssselect >=0.9
        - w3lib >=1.8.0
        - queuelib
        - six >=1.5.2

    run:
        - python
        - setuptools
        - twisted >=10.0.0
        - lxml
        - pyopenssl
        - cssselect >=0.9
        - w3lib >=1.8.0
        - queuelib
        - six >=1.5.2

test:
    imports:
        - scrapy

    commands:
        #- nosetests -w tests/

about:
    home: https://github.com/louist87/Scrappy
    license: GPL v3

