package:
  name: jq
  version: 1.3

source:
  fn: jq-1.3.tar.gz
  url: http://stedolan.github.io/jq/download/source/jq-1.3.tar.gz
  md5: 26081b05d22525eca5cbdd8f9f4db17d

build:
  number: 1

about:
    home: http://stedolan.github.io/jq/
    license:  MIT
