package:
  name: pybars3
  version: "0.9.1"

source:
  fn: pybars3-0.9.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pybars3/pybars3-0.9.1.tar.gz
  md5: 38ef2da87fa70af7d8a8a9908b732cee
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pybars3 = pybars3:main
    #
    # Would create an entry point called pybars3 that calls pybars3.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - pymeta3 >=0.5.1

  run:
    - python
    - pymeta3 >=0.5.1

test:
  # Python imports
  imports:
    - pybars
    - pybars._templates

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/wbond/pybars3
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Handlebars.js templating for Python 3 and 2'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
