package:
  name: db.py
  version: !!str 0.4.3

source:
  git_url: https://github.com/yhat/db.py.git
  patches:
    - build.patch

requirements:
  build:
    - python
    - setuptools
    - prettytable >=0.7.2
    - pandas
    - pybars3

  run:
    - python
    - prettytable >=0.7.2
    - pandas
    - pybars3

test:
  # Python imports
  imports:
    - db
    - db.queries
    - db.tests

about:
  home: https://github.com/yhat/db.py
  license: BSD License
  summary: "a db package that doesn't suck"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
