package:
  name: rosetta
  version: !!str 0.2.5

source:
  fn: rosetta-0.2.5.tar.gz
  url: https://pypi.python.org/packages/source/r/rosetta/rosetta-0.2.5.tar.gz
  md5: 263d1bb253c0d9f510527be97fc38472
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rosetta = rosetta:main
    #
    # Would create an entry point called rosetta that calls rosetta.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - pandas
    - scikit-learn
    - statsmodels
    - gensim
    - docx
    - pyth
    - pymongo
    - mysql-python
    - scipy
    - nltk

  run:
    - python
    - pandas
    - scikit-learn
    - statsmodels
    - gensim
    - docx
    - pyth
    - pymongo
    - mysql-python
    - scipy
    - nltk

test:
  # Python imports
  imports:
    - rosetta
    - rosetta.cmd
    - rosetta.modeling
    - rosetta.parallel
    - rosetta.text
    - rosetta.workflow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/columbia-applied-data-science/rosetta
  license: BSD
  summary: 'Tools, wrappers, etc... for data science with a concentration on text processing'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
