package:
  name: word2vec
  version: !!str 0.6.7

source:
  fn: word2vec-0.6.7.tar.gz
  url: https://pypi.python.org/packages/source/w/word2vec/word2vec-0.6.7.tar.gz
  md5: f44bf1ebd1f6adcad7635dd178686c47
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - word2vec = word2vec:main
    #
    # Would create an entry point called word2vec that calls word2vec.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy >=1.7.1

  run:
    - python
    - numpy >=1.7.1

test:
  # Python imports
  imports:
    - word2vec

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/danielfrg/word2vec
  license: Apache License Version 2.0, January 2004
  summary: 'Google word2vec python wrapper'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
