package:
  name: funcy
  version: "1.6"

source:
  fn: funcy-1.6.tar.gz
  url: https://pypi.python.org/packages/source/f/funcy/funcy-1.6.tar.gz
  md5: 41c5e1555077334ee1a669416863df68
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - funcy = funcy:main
    #
    # Would create an entry point called funcy that calls funcy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - funcy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/Suor/funcy
  license: BSD License
  summary: 'A fancy and practical functional tools'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
