package:
  name: faulthandler
  version: 2.4

source:
  fn: faulthandler-2.4.tar.gz
  url: https://pypi.python.org/packages/source/f/faulthandler/faulthandler-2.4.tar.gz
  md5: 110960933b0902334e8804eb4ea20750
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - faulthandler = faulthandler:main
    #
    # Would create an entry point called faulthandler that calls faulthandler.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - faulthandler

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/haypo/faulthandler/wiki/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
