package:
  name: librato-metrics
  version: !!str 0.8.1

source:
  fn: librato-metrics-0.8.1.tar.gz
  url: https://pypi.python.org/packages/source/l/librato-metrics/librato-metrics-0.8.1.tar.gz
  md5: 4fe23a6b32dcc1fc91d4bbe7101c29a4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - librato-metrics = librato-metrics:main
    #
    # Would create an entry point called librato-metrics that calls librato-metrics.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - librato

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/librato/python-librato
  license: MIT License
  summary: 'Python API Wrapper for Librato'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
