
package:
    name: wordcloud
    version: !!str 1.0

source:
    git_url: https://github.com/amueller/word_cloud                                         

build:
    number: 1

requirements:
    build:
        - python
        - cython
        - image
        - numpy

    run:
        - python
        - cython
        - image
        - numpy
test:
    imports:
        - wordcloud

about:
    home: https://github.com/amueller/word_cloud
