package:
  name: dm
  version: "1.3"

source:
  fn: dm-1.3.tar.gz
  url: https://pypi.python.org/packages/source/d/dm/dm-1.3.tar.gz
  md5: 97945153d296f6ab2e18b285123ffead
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dm = dm:main
    #
    # Would create an entry point called dm that calls dm.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - dm

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: GPL
  summary: 'Dict to Data mapper'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
