package:
  name: dnsq
  version: !!str 1.1.3

source:
  fn: dnsq-1.1.3.tar.gz
  url: https://pypi.python.org/packages/source/d/dnsq/dnsq-1.1.3.tar.gz
  md5: 45ccb3a0248829452999f70ac84e7024
  patches:
   # List any patch files here
    - build.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dnsq = dnsq:main
    #
    # Would create an entry point called dnsq that calls dnsq.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - dnspython >=1.11.1
    - expiringdict >=1.1

  run:
    - python
    - dnspython >=1.11.1
    - expiringdict >=1.1

test:
  # Python imports
  imports:
    - dnsq

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.mailgun.com
  license: Apache 2
  summary: 'DNS Query Tool'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
