package:
  name: pybrain
  version: !!str 0.3.3

source:
  fn: PyBrain-0.3.3.tar.gz
  url: https://github.com/pybrain/pybrain/archive/0.3.3.tar.gz
  md5: 39b2b222e67d8f195b4daa0f8000979d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pybrain = pybrain:main
    #
    # Would create an entry point called pybrain that calls pybrain.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - pyode

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pyode

test:
  # Python imports
  imports:
    - pybrain

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pybrain.org
  license: BSD License
  summary: 'PyBrain is the swiss army knife for neural networking.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
