
package:
    name: scala
    version: 2.11.5

source:
    fn: scala-2.11.5.tgz
    url: http://downloads.typesafe.com/scala/2.11.5/scala-2.11.5.tgz

build:
    number: 0

requirements:
    build:

    run:

test:
    commands:
        - scalac -help

about:
    home: http://www.scala-lang.org/
    license: 3-clause BSD license
