package:
  name: nolearn
  version: !!str 0.5b1

source:
  fn: nolearn-0.5b1.tar.gz
  url: https://pypi.python.org/packages/source/n/nolearn/nolearn-0.5b1.tar.gz
  md5: 1824f5ec0f4ea3dbd4648bf69ce071a8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nolearn = nolearn:main
    #
    # Would create an entry point called nolearn that calls nolearn.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docopt
    - gdbn
    - joblib
    - scikit-learn

  run:
    - python
    - docopt
    - gdbn
    - joblib
    - scikit-learn

test:
  # Python imports
  imports:
    - nolearn
    - nolearn.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dnouri/nolearn
  license: MIT
  summary: 'scikit-learn compatible wrappers for neural net libraries, and other utilities.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
