package:
  name: sip
  version: 4.16.5

source:
  fn: sip-4.16.5.tar.gz # [unix]
  url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz # [unix]
  sha1: d5d7b6765de8634eccf48a250dbd915f01b2a771 # [unix]
  fn: sip-4.16.5.zip # [win]
  url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.zip # [win]
  sha1: fa6c055a3db805218bd962a9fb182aa0bf91f95e # [win]

requirements:
  build:
    - python
    - python.app # [osx]

  run:
    - python

test:
  imports:
    - sip

  files:
    - test

  commands:
    - sip -c test test/word.sip

about:
  home: http://www.riverbankcomputing.com/software/sip/intro
  license: GPL
