package:
  name: qwt
  version: 6.1.2

source:
  fn: qwt-6.1.2.tar.bz2
  url: http://sourceforge.net/projects/qwt/files/qwt/6.1.2/qwt-6.1.2.tar.bz2/download
  md5: 9c88db1774fa7e3045af063bbde44d7d
  patches:
    - build.patch

requirements:
  build:
    - qt
  run:
    - qt

about:
  home: http://www.crummy.com/software/BeautifulSoup/
  license: BSD
