package:
  name: blaze
  version: "0.7.0"

source:
  fn: blaze-0.7.0.tar.gz
  url: https://pypi.python.org/packages/source/b/blaze/blaze-0.7.0.tar.gz
  md5: 492b94819842ec5a8a53aeb4362c280c

build:
    number: 1

requirements:
  build:
    - python
    - numpy
    - multipledispatch
    - sqlalchemy
    - pandas
    - h5py
    - datashape
    - into
    - flask
    - requests
    - cytoolz
    - toolz
    - bcolz
    - pytables
    - psutil
    - into
    - pymongo
    - pytest
    - unittest2 [py26]

  run:
    - python
    - numpy
    - multipledispatch
    - sqlalchemy
    - pandas
    - h5py
    - datashape
    - into
    - flask
    - requests
    - cytoolz
    - toolz
    - bcolz
    - pytables
    - psutil
    - into
    - pymongo
    - unittest2 [py26]

test:
  requires:
    - pytest
    - coverage

  commands:
    - python -c "import blaze; blaze.test()"

about:
  home: http://blaze.pydata.org
  license: BSD