package:
  name: graphlab-create
  version: !!str 1.5.2

source:
  fn: GraphLab_Create-1.5.2-cp27-none-macosx_10_5_x86_64.macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  url: https://pypi.python.org/packages/cp27/G/GraphLab-Create/GraphLab_Create-1.5.2-cp27-none-macosx_10_5_x86_64.macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  md5: 601d0645a1f461e3b032a7fe5071c1fe
  #patches:
   # List any patch files here
    #- build.patch

build:
  number: 1


requirements:
  build:
      - python
      - setuptools
      - boto >=2.33.0
      - librato-metrics >=0.4.9
      - mixpanel-py >=3.1.1
      - decorator >=3.4.0
      - tornado >=4.1
      - prettytable >=0.7.2
      - requests >=2.3.0
      - awscli >=1.6.2
      - lockfile >=0.10.2
      - flask-cors >=1.10.3
      - httpretty >=0.8.3
      - flask >=0.10.1
      - flask-restful >=0.3.0
      - sseclient >=0.0.8
      - multipledispatch >=0.4.7
    

  run:
    - python
    - setuptools
    - boto >=2.33.0
    - librato-metrics >=0.4.9
    - mixpanel-py >=3.1.1
    - decorator >=3.4.0
    - tornado >=4.1
    - prettytable >=0.7.2
    - requests >=2.3.0
    - awscli >=1.6.2
    - lockfile >=0.10.2
    - flask-cors >=1.10.3
    - httpretty >=0.8.3
    - flask >=0.10.1
    - flask-restful >=0.3.0
    - sseclient >=0.0.8
    - multipledispatch >=0.4.7
    
    
test:
  # Python imports
  imports:
    - graphlab
    - graphlab.canvas
    - graphlab.canvas.views
    - graphlab.connect
    - graphlab.connect.aws
    - graphlab.cython
    - graphlab.data_structures
    - graphlab.deploy
    - graphlab.deploy._predictive_service
    - graphlab.deps
    - graphlab.meta
    - graphlab.meta.asttools
    - graphlab.meta.asttools.mutators
    - graphlab.meta.asttools.visitors
    - graphlab.meta.bytecodetools
    - graphlab.meta.decompiler
    - graphlab.meta.scripts
    - graphlab.toolkits
    - graphlab.toolkits.classifier
    - graphlab.toolkits.clustering
    - graphlab.toolkits.deeplearning
    - graphlab.toolkits.graph_analytics
    - graphlab.toolkits.image_analysis
    - graphlab.toolkits.nearest_neighbors
    - graphlab.toolkits.recommender
    - graphlab.toolkits.regression
    - graphlab.toolkits.text_analytics
    - graphlab.toolkits.topic_model
    - graphlab_psutil
    - graphlab_util

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://graphlab.com
  license: LICENSE.txt
  summary: 'GraphLab Create enables developers and data scientists to apply machine learning to build state of the art data products.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
