package:
    name: graphreduce
    version: !!str 0.2

source:
    git_url: https://github.com/timmytw/graphreduce.git                                             

build:
    number: 0

requirements:
    build:
        - python
        - graphlab-create
    run:
        - python
        - graphlab-create

test:
    imports:
        - graphreduce

about:
    home: https://github.com/timmytw/graphreduce
