package:
  name: phonenumbers
  version: "7.4.1"

source:
  fn: phonenumbers-7.4.1.tar.gz
  url: https://github.com/daviddrysdale/python-phonenumbers/archive/release-7.4.1.tar.gz
  md5: 81d433ec313887f47daaa8652371193e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - phonenumbers = phonenumbers:main
    #
    # Would create an entry point called phonenumbers that calls phonenumbers.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  license: Apache Software License
  summary: u"Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
