package:
  name: r-mass
  version: 7.3.37

source:
  fn: MASS_7.3-37.tar.gz
  url: http://cran.r-project.org/src/contrib/MASS_7.3-37.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: lattice, nlme, nnet, survival
requirements:
  build:
    - r >=3.0.0
  run:
    - r >=3.0.0

test:
  commands:
    - R -e "library('MASS')"

about:
  license: GPL-2 | GPL-3
