package:
  name: scs
  version: 1.0.7

source:
  fn: scs-1.0.7.zip [not win]
  url: https://github.com/cvxgrp/scs/archive/v1.0.7.zip


build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - scipy
  run:
    - python
    - numpy
    - scipy
test:
  imports:
    - scs

about:
  home: https://github.com/cvxgrp/scs
  license: MIT

# vim:set ts=8 sw=2 sts=2 tw=78 et:
