package:
  name: data_hacks
  version: !!str 0.3

source:
  fn: data_hacks-0.3.tar.gz
  url: https://pypi.python.org/packages/source/d/data_hacks/data_hacks-0.3.tar.gz
  md5: 44a66968ed7449f05e8fbf23d3f0c58c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - data_hacks = data_hacks:main
    #
    # Would create an entry point called data_hacks that calls data_hacks.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

#test:
  # Python imports
  #imports:
  #  - data_hacks

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/bitly/data_hacks
  license: BSD
  summary: 'Command line utilities for data analysis'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
