package:
  name: jug
  version: !!str 1.0.1

source:
  fn: Jug-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/J/Jug/Jug-1.0.1.tar.gz
  md5: 4f38c3c0891d5b941aba4a2ad1394a0d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - jug = jug:main
    #
    # Would create an entry point called jug that calls jug.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six
    - redis
    - redis-py

  run:
    - python
    - six
    - redis
    - redis-py

test:
  # Python imports
  imports:
    - jug
    - jug.backends
    - jug.subcommands
    - jug.tests
    - jug.tests.jugfiles

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://luispedro.org/software/jug
  license: MIT License
  summary: 'A Task Based Parallelization Framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
