package:
  name: milk
  version: 0.5.3

source:
  fn: milk-0.5.3.tar.gz
  url: https://pypi.python.org/packages/source/m/milk/milk-0.5.3.tar.gz
  md5: 54a14d9b28b05196f8988ebdf1ef5c16
  patches:
   # List any patch files here
    - build.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - milk:main
    #
    # Would call milk.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - milk

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: http://luispedro.org/software/milk
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
