package:
  name: libsvm
  version: !!str 3.20

source:
  fn: libsvm-3.20.tar.gz
  sha1: 6902c22afadc70034c0d1c0e25455df10fb01eaf
  url: http://www.csie.ntu.edu.tw/~cjlin/libsvm/libsvm-3.20.tar.gz
  patches:
    - build.patch
  
build:
  number: 2
  
requirements:
  build:
    - python
test:
  imports:
    - svm
    - svmutil


about:
  home: http://www.csie.ntu.edu.tw/~cjlin/libsvm/