package:
  name: xlwings
  version: !!str 0.3.5

source:
  fn: xlwings-0.3.5.tar.gz
  url: https://pypi.python.org/packages/source/x/xlwings/xlwings-0.3.5.tar.gz
  md5: 8ea2d1f7a0a1a0d05032754a625cf480

requirements:
  build:
    - python
    - pywin32 # [win]
    - psutil # [osx]
    - appscript # [osx]
    - pandas

  run:
    - python
    - pywin32 # [win]
    - psutil # [osx]
    - appscript # [osx]
    - pandas

test:
  imports:
   - xlwings

about:
  home: http://xlwings.org
  license: BSD

# vim:set ts=8 sw=2 sts=2 tw=78 et:
