package:
  name: xray
  version: "0.4.1"

source:
  fn: xray-0.4.1.tar.gz
  url: https://pypi.python.org/packages/source/x/xray/xray-0.4.1.tar.gz
  md5: 38d230c3284520f370b3821bb0b87863
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - xray = xray:main
    #
    # Would create an entry point called xray that calls xray.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - pandas >=0.15.0

  run:
    - python
    - numpy >=1.7
    - pandas >=0.15.0

test:
  # Python imports
  imports:
    - xray
    - xray.backends
    - xray.core
    - xray.test

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/xray/xray
  license: Apache Software License
  summary: 'N-D labeled arrays and datasets in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
