package:
  name: mpich2
  version: !!str 3.1.3

source:
  fn: mpich-3.1.3.tar.gz
  url: http://www.mpich.org/static/downloads/3.1.3/mpich-3.1.3.tar.gz
  sha1: aa9907891ef4a4a584ab2f90a86775f29ca0dec0

test:
  commands:
    - mpicc --help

about:
  home: http://www.mpich.org