package:
  name: mechanicalsoup
  version: !!str 0.2.1

source:
  fn: MechanicalSoup-0.2.1.zip
  url: https://pypi.python.org/packages/source/M/MechanicalSoup/MechanicalSoup-0.2.1.zip
  md5: 6788c5fe59be35adf22f17889f15ee0a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mechanicalsoup = mechanicalsoup:main
    #
    # Would create an entry point called mechanicalsoup that calls mechanicalsoup.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests
    - beautiful-soup
    - six

  run:
    - python
    - requests
    - beautiful-soup
    - six

test:
  # Python imports
  imports:
    - mechanicalsoup

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/matt-hickford/MechanicalSoup
  license: MIT License
  summary: 'A Python library for automating interaction with websites'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
