package:
  name: ipyparallel
  version: "5.0.0"

source:
  fn: ipyparallel-5.0.0.tar.gz
  url: https://pypi.python.org/packages/source/i/ipyparallel/ipyparallel-5.0.0.tar.gz
  md5: 1da73215994858bcaf62f1daad6366ef

requirements:
  build:
    - python
    - futures               # [py2k]
    - decorator
    - tornado >=4
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel
    - tornado >=4

  run:
    - python
    - futures               # [py2k]
    - decorator
    - tornado >=4
    - pyzmq >=13
    - ipython_genutils
    - ipython >=4
    - jupyter_client
    - ipykernel

test:
  imports:
    - ipyparallel
    - ipyparallel.apps
    - ipyparallel.client
    - ipyparallel.controller
    - ipyparallel.engine
    - ipyparallel.serialize

about:
  home: http://ipython.org
  license: BSD License
  summary: 'Interactive Parallel Computing with IPython'
