
package:
    name: pycuda
    version: !!str 2015.1.2

source:
    fn: pycuda-2015.1.2.tar.gz
    url: https://pypi.python.org/packages/source/p/pycuda/pycuda-2015.1.2.tar.gz
    md5: 829c828c90f02dda25f8ec326e53e907

build:
    number: 0

requirements:
    build:
        - python
        - distribute
        - numpy
        - decorator
        - pytest
        - pytools

    run:
        - python
        - numpy
        - decorator

test:
    imports:
        - pycuda

about:
    home: http://mathema.tician.de/software/pycuda/
    license: MIT
