package:
  name: sheets
  version: !!str 0.6_dev

source:
  git_url: git@github.com:derickl/sheets.git

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - sheets

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://propython.com/
  license: BSD License
  summary: 'A declarative class framework for working with CSV files'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
