package:
  name: rodeo
  version: "0.4.1"

source:
  fn: rodeo-0.4.1.tar.gz
  url: https://pypi.python.org/packages/source/r/rodeo/rodeo-0.4.1.tar.gz
  md5: 33979e3f14445c9c32bbb169cff51495
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rodeo = rodeo:main
    #
    # Would create an entry point called rodeo that calls rodeo.main()

    - rodeo = rodeo.cli:cmd

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - ipython >=3.0.0
    - flask >=0.10.1
    - docopt
    - pyzmq >=13
    - docopt
    - mistune

  run:
    - python
    - ipython >=3.0.0
    - flask >=0.10.1
    - jedi
    - pyzmq >=13
    - pip
    - docopt
    - mistune
    

test:
  # Python imports
  imports:
    - rodeo

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - rodeo --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/yhat/rodeo/
  license: BSD
  summary: 'an ide for data analysis in python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

app:
  entry: rodeo .
  summary: "Rodeo is an IDE that's built expressly for doing data science in Python."
