package:
  name: r-kernsmooth
  version: 2.23.13

source:
  fn: KernSmooth_2.23-13.tar.gz
  url: http://cran.r-project.org/src/contrib/KernSmooth_2.23-13.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - r >=2.5.0
  run:
    - r >=2.5.0

test:
  commands:
    - R -e "library('KernSmooth')"

about:
  license: Unlimited
