package:
  name: disco
  version: 0.5.4

source:
  git_url: git@github.com:discoproject/disco.git
  git_tag: 0.5.4
  patches:
    - build.patch
    
build:
  number: 2

requirements:
  build:
    - python
    - erlang
    - simplejson
    - libcmph
    
  run:
    - python
    - erlang
    - simplejson
    - libcmph
    
test:
  imports:
    - disco

about:
  home: http://discoproject.org/
  license: BSD
