package:
  name: disco
  version: 0.5.4

source:
  fn: disco-0.5.4.tar.gz
  url: https://github.com/discoproject/disco/archive/0.5.4.tar.gz
  sha1: 43bc8fac5d5d657a81a8d7b628d1f72f97470b6e
  patches:
    - build.patch
   #  - no-listdir.patch
   # - prefix-erl.patch
    
build:
  number: 0

requirements:
  build:
    - python
    - erlang
    - simplejson
    - libcmph
    
  run:
    - python
    - erlang
    - simplejson
    - libcmph
    
test:
  imports:
    - disco

about:
  home: http://discoproject.org/
  license: BSD
