package:
  name: orange
  version: 2.7.8

source:
  fn: Orange-2.7.8.tar.gz
  url: https://pypi.python.org/packages/source/O/Orange/Orange-2.7.8.tar.gz
  md5: 44656527ef3ac9874ac4d1c9f35f70ee

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - BeautifulSoup

about:
  home: http://www.crummy.com/software/BeautifulSoup/
  license: BSD
