package:
  name: pandasql
  version: 0.6.3

source:
  fn: pandasql-0.6.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pandasql/pandasql-0.6.3.tar.gz
  md5: b6b8bded04d8df5876ab7b8fd8161e21
 # patches:
    #- sqlparse_version.patch

requirements:
  build:
    - python
    - setuptools
    - sqlparse
  run:
    - python
    - sqlparse
    - pandas
    - numpy

test:
  imports:
    - pandasql

about:
  home: https://github.com/yhat/pandasql
  license: BSD
