package:
  name: upoints
  version: "0.12.2"

source:
  fn: upoints-0.12.2.tar.gz
  url: https://pypi.python.org/packages/source/u/upoints/upoints-0.12.2.tar.gz
  md5: 5baeaecc30e83dead825d12ef354b745
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - upoints = upoints:main
    #
    # Would create an entry point called upoints that calls upoints.main()

    - edist = upoints.edist:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - aaargh >=0.7
    - lxml

  run:
    - python
    - aaargh >=0.7
    - lxml

test:
  # Python imports
  imports:
    - upoints

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - edist --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/JNRowe/upoints/
  license: GNU General Public License (GPL) or GNU General Public License v3 or later (GPLv3+)
  summary: 'Modules for working with points on Earth'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
