package:
  name: image
  version: !!str 1.3.4

source:
  fn: image-1.3.4.tar.gz
  url: https://pypi.python.org/packages/source/i/image/image-1.3.4.tar.gz
  md5: 44c77b417a19d0a4efb17338d0697955
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - image = image:main
    #
    # Would create an entry point called image that calls image.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pillow
    - django

  run:
    - python
    - pillow
    - django

test:
  # Python imports
  imports:
    - image
    - image.templatetags

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/francescortiz/image
  license: BSD
  summary: 'Django application that provides cropping, resizing, thumbnailing, overlays and masking for images and videos with the ability to set the center of attention,'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
