package:
  name: ode
  version: !!str 0.13.1

source:
  fn: ode-0.13.1.tar.bz2
  url: https://bitbucket.org/odedevs/ode/downloads/ode-0.13.1.tar.gz
  sha1: 2fea08792e8f0fe606e929097fbec78ba926bcab

build:
  number: 1
about:
  home: http://www.ode.org/
  license: BSD

